// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { getClientEnv } from '@/lib/env';
import type { Database } from './types';

function createSupabaseClient() {
  const { VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY } = getClientEnv();

  return createClient<Database>(VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

